"""adiciona tabela de e-mails enviados

Revision ID: e69fa096ec95
Revises: 
Create Date: 2026-10-04 19:22:57.136295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69fa096ec95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('de', sa.String(length=100), nullable=True),
    sa.Column('para', sa.String(length=300), nullable=True),
    sa.Column('assunto', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails_enviados')
    # ### end Alembic commands ###
